fail_fast: false
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.1
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
      - id: clang-tidy
        args:
          [
            "-p=build",
            "--header-filter=/home/lukasnee/dev/1/fibration/extern/ln/ln/.*",
            "--extra-arg=--target=arm-none-eabi",
            "--extra-arg=-isystem/opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/14.3.1",
            "--extra-arg=-isystem/opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/14.3.1/arm-none-eabi/thumb/v7e-m+dp/hard",
            "--extra-arg=-isystem/opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/14.3.1/backward",
            "--extra-arg=-isystem/opt/gcc-arm-none-eabi/arm-none-eabi/include",
          ]
      # - id: cppcheck # TODO: try out cppcheck
      # - id: cpplint # TODO: try out cpplint
      # - id: include-what-you-use
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
      - id: cmake-format
    # - id: cmake-lint # default configuration seems too strict, could be
    #   revisited later
  - repo: local
    hooks:
      - id: cmake-project-build-check
        name: CMake Project Build Check
        entry: cmake --build --preset main-dbg
        language: system
        files: \.(c|cpp|h|hpp|cmake|CMakeLists\.txt)$
        pass_filenames: false
        description: Ensures the project builds successfully with CMake
